---

- name: Stat backup target
  stat: path={{ sab_backup_target }}
  register: backup_dir

- name: Create backup dir
  file: path={{ sab_backup_target }}
        state=directory
        owner=root
        group=root
  when: backup_dir.stat.exists == False

- name: Stat backup script dir
  stat: path={{ sab_backup_script_dir }}
  register: backup_script_dir

- name: Create backup script dir
  file: path={{ sab_backup_script_dir }}
        state=directory
        owner=root
        group=root
  when: backup_script_dir.stat.exists == False

- name: Create backup script
  template: src=sabnzbd_backup.sh.j2
            dest="{{ sab_backup_script_dir }}/sabnzbd_backup.sh"
            owner=root
            group=root
            mode="a+x"

- name: Create cron backup
  cron: name="Sabnzbd Backup"
        hour="04"
        minute="10"
        user="root"
        job="{{ sab_backup_script_dir }}/sabnzbd_backup.sh"
        state=present
