---
# Guides:
  #: http://www.digitesters.com/install-sabnzbd-on-centos-7/

- name: Create download dirs
  file: dest="{{ sab_download_dir }}/{{ item }}"
        state=directory
        recurse=yes
        owner={{ stack_user }}
        group={{ stack_user_group }}
  with_items:
      - complete/movies
      - complete/tvshows
      - complete/music
      - incomplete
      - nzb_watched
      - nzb_backup

- name: Install prerequisites
  yum:  pkg={{ item }}
        state=installed
        update_cache=yes
  with_items:
      # Common
      - wget
      - git
      # Compiler
      - gcc
      - gcc-c++
      - libgcc
      - make
      - cmake
      # Python
      - python
      - python-libs
      - python-configobj
      - python-pycurl
      - python-pyudev
      - python-setuptools
      - python-cheetah
      - python-devel
      - python-tools
      - python-feedparser
      - par2cmdline     
      - pyOpenSSL
      # OpenSSL
      - openssl
      - openssl-devel
      - openssl-libs
      # Compression
      - gzip
      - bzip2
      - p7zip
      - unrar
      - unzip

  # par2 multicore guide
  # https://forums.sabnzbd.org/viewtopic.php?f=16&t=18793#p99702

- name: Yenc --> Extract file
  unarchive:
    src: "{{ sab_yenc_link }}"
    dest: "/tmp"
    copy: no
  sudo: yes
  when: downloaded_yenc|changed

- name:     Yenc --> Build
  command:  python setup.py build
  args:
    chdir: "/tmp/{{ sab_yenc_name }}"

- name:     Yenc --> Install
  command:  python setup.py install
  args:
    chdir: "/tmp/{{ sab_yenc_name }}"

- name: Yenc --> Remove files
  file: path="/tmp/{{ sab_yenc_name }}"
        state=absent

  #pyOpenSSL
- name: pyOpenSSL --> Download file
  command: pip install pyopenssl
  sudo: yes

- name: Clone repo
  git:  repo="{{ sab_repo }}"
        dest={{ sab_install_dir }}

- name: Create data dir
  file: dest={{ sab_config_dir }}
        state=directory
        recurse=yes
        owner="{{ stack_user }}"
        group="{{ stack_user_group }}"

- block:

    - name: Get the latest backup file
      command: "ls {{ sab_backup_target }}/sabnzbd -t | head -1"
      register: result_backup_file

    - name: Set Fact for sab_restore_file
      set_fact:
        sab_restore_file: "{{ sab_backup_target }}/{{ result_backup_file.stdout_lines }}"

  when:
    - sab_restore_from_backup
    # - not sab_restore_file is defined

- name: Restore Backup --> Extract archive
  unarchive:
    src: "{{ sab_restore_file }}"
    dest: "{{ sab_config_dir }}"
    copy: no
    owner: "{{ stack_user }}"
    group: "{{ stack_user_group }}"
  sudo: yes
  when: sab_restore_file is defined

- name: Enable port on firewall
  command: "{{ item }}"
  with_items:
    - firewall-cmd --permanent --add-port=8080/tcp  # HTTP port
    - firewall-cmd --permanent --add-port=9090/tcp  # HTTPS port
    - firewall-cmd --reload
  sudo: yes
  when: firewall_enabled

- name: Add service
  template: src=sabnzbd.service.j2
            dest=/etc/systemd/system/sabnzbd.service
            owner=root group=root mode=0644

- name: Enable service
  service:  name=sabnzbd.service
            enabled=yes
            state=started
