---
# Guides:
  #: http://www.digitesters.com/install-sabnzbd-on-centos-7/

- name: Create Group
  group:
    name: "{{ sab_group }}"
    system: no
    state: present 
  become: true

- name: Create User
  user:
    name: "{{ sab_user }}"
    group: "{{ sab_group }}"
    state: present
    system: no
    createhome: no
    shell: /bin/false
  become: true

- name: Create dirs
  file: dest="{{ item }}"
        state=directory
        recurse=yes
        owner={{ sab_user }}
        group={{ sab_group }}
  with_items:
    - "{{ sab_download_dir }}/complete/movies"
    - "{{ sab_download_dir }}/complete/tvshows"
    - "{{ sab_download_dir }}/complete/music"
    - "{{ sab_download_dir }}/incomplete"
    - "{{ sab_download_dir }}/nzb_watched"
    - "{{ sab_download_dir }}/nzb_backup"
    - "{{ sab_install_dir }}"
    - "{{ sab_config_dir }}"
  become: true

- name: Install prerequisites
  yum:  pkg={{ item }}
        state=installed
        update_cache=yes
  with_items:
      # Common
      - wget
      - git
      # Compiler
      - gcc
      - gcc-c++
      - libgcc
      - make
      - cmake
      # Python
      - python
      - python-libs
      - python-configobj
      - python-pycurl
      - python-pyudev
      - python-setuptools
      - python-cheetah
      - python-devel
      - python-tools
      - python-feedparser
      - par2cmdline     
      - pyOpenSSL
      # OpenSSL
      - openssl
      - openssl-devel
      - openssl-libs
      # Compression
      - gzip
      - bzip2
      - p7zip
      - unrar
      - unzip

  # par2 multicore guide
  # https://forums.sabnzbd.org/viewtopic.php?f=16&t=18793#p99702

- name: Install Pip Modules
  command: "pip install {{ item }} --upgrade"
  with_items:
    - sabyenc
    - cryptography
    - pyopenssl
  become: true

- name: Clone repo
  git:  repo="{{ sab_repo }}"
        dest={{ sab_install_dir }}

- block:

    - name: Get files from sab_backup_target
      find:
        paths: "{{ sab_backup_target }}"
      register: found_files

    - name: Get latest backup file
      set_fact:
        __sab_restore_file: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first  }}"

    - name: Set Fact for sab_restore_file
      set_fact:
        sab_restore_file: "{{ __sab_restore_file.path }}"

  when:
    - sab_restore_from_backups
    
- name: Restore Backup --> Extract archive
  unarchive:
    src: "{{ sab_restore_file }}"
    dest: "{{ sab_config_dir }}"
    copy: no
    owner: "{{ sab_user }}"
    group: "{{ sab_group }}"
  become: yes
  when: sab_restore_file is defined

- name: Enable port on firewall
  command: "{{ item }}"
  with_items:
    - firewall-cmd --permanent --add-port=8080/tcp  # HTTP port
    - firewall-cmd --permanent --add-port=9090/tcp  # HTTPS port
    - firewall-cmd --reload
  become: yes
  when: sab_firewall_enabled

- name: Add service
  template: src=sabnzbd.service.j2
            dest=/etc/systemd/system/sabnzbd.service
            owner=root group=root mode=0644
  notify:
    - start sab
