---
- name: Check if installed
  stat: path="{{ sab_install_dir }}"
  register: check_installed

- name: CentOS Install
  include: "install.yml"
  when: check_installed.stat.exists == False

- name: Configure Backups
  include: "backups.yml"
  when: sab_backups_enabled

- name: Update
  git:
    repo: "{{ sab_repo }}"
    dest: "{{ sab_install_dir }}"
    version: master
    update: yes
  notify:
    - restart sab
  when:
    - check_installed.stat.exists
    - sab_allow_update