---
- name: Check if installed
  stat: path="{{ sab_install_dir }}"
  register: check_installed

- name: CentOS Install
  include: "install.yml"
  when:
    - ansible_distribution == 'CentOS'
    - check_installed.stat.exists == False

- name: Configure Backups
  include: "backups.yml"
  when:
    - ansible_distribution == 'CentOS'
    - sab_backups_enabled

- name: Update
  include: "upgrade.yml"
  when:
    - ansible_distribution == 'CentOS'
    - check_installed.stat.exists
    - sab_allow_update